## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [5]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [6]:
# Type your solution here
import numpy as np
import pandas as pd
# Q1-1: Write a program that create a dataframe from the data.
frame = pd.DataFrame(data)
print(frame)
# Q1-2: Select people that are psychologist or teacher and their number of cars is greater than their family size.
frame[((frame["job"] == "psychologist") | (frame["job"] == "teacher")) & (frame["num_cars"]>frame["family_size"])]

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [7]:
# Q1-3: Select people who have at most 2 family members and at least 1 car.
frame["family_size"] = frame["family_size"].astype(str)
frame["num_cars"] = frame["num_cars"].astype(str)
frame[((frame["family_size"] <= "2") & (frame["num_cars"] >= "1"))]

name             job family_size num_cars
1  Jacob    psychologist           2        1
2    Sam  data scientist           1        1
4   Ryan    psychologist           2        2
6    Lee         teacher           2        1

In [8]:
# Q1-4: Write a code that get number of unique jobs in this dataset.
unique = frame["job"].nunique()
print("Number of unique jobs:", unique, end="\n\n")
print("Following are specific numbers of each job:")
count = frame["job"].value_counts()
print(count)

Number of unique jobs: 4

Following are specific numbers of each job:
psychologist          3
teacher               2
data scientist        1
software developer    1
Name: job, dtype: int64


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [12]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [20]:
# Type your solution here
# dict1 = fruit.value_counts().to_json()
# dict2 = weights.to_json()
print("The following are means of weights of each fruit:")
mean = weights.groupby(fruit).mean()
print(mean)

The following are means of weights of each fruit:
apple     7.250000
banana    3.666667
carrot    5.000000
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
# Q3-1: Write a NumPy program to get the indices of the sorted elements of course_name array.
indicies = np.argsort(course_name)
print("Indices of the sorted elements of course_name array:")
print(indicies, end="\n\n")
# Q3-2: Write numpy code to check whether each element of course_name array starts with "P".
checker = np.char.startswith(course_name, "P")
print("Result of checking whether each element of course_name array starts with 'P': ")
print(checker)

Indices of the sorted elements of course_name array:
[1 3 0 2 4]

Result of checking whether each element of course_name array starts with 'P': 
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
# Q4-1: Reverse the student_id array. Print both original and reversed array.
reverse = student_id[::-1]
print("array:", student_id, "\nreverse array:", reverse, end="\n\n")
# Q4-2: Get the 3-largest values of student_id array.
sorted = np.sort(reverse)
result = sorted[len(sorted)-3:]
print("The 3-largest values of student_id array are:", result)

array: [6230 5241 5202 4532 1682 1671 1023] 
reverse array: [1023 1671 1682 4532 5202 5241 6230]

The 3-largest values of student_id array are: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
# Hint: you can use arange to start off
import numpy as np
range = np.arange(1,100)
three_multiples = range[(range % 3 == 0)]
print("All the multiples of 3:", three_multiples)
three_sum = three_multiples.sum()
print("Sum of all the multiples of 3:", three_sum, "\n\n")
five_multiples = range[(range % 5 == 0)]
print("All the multiples of 3:", five_multiples)
five_sum = five_multiples.sum()
print("Sum of all the multiples of 5:", five_sum, "\n\n")
multiples = range[(range % 3 == 0) | (range % 5 == 0)]
print("All the multiples of 3 or 5:", multiples)
sum = multiples.sum()
print("Sum of all the multiples of 3 or 5:", sum)

All the multiples of 3: [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
Sum of all the multiples of 3: 1683 


All the multiples of 3: [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Sum of all the multiples of 5: 950 


All the multiples of 3 or 5: [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum of all the multiples of 3 or 5: 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
# Q6.1. Write a code to swap column 1 with column 2.
new_array = arr[:,[1,0,2,3]]
print("New array after swap column 1 with column 2 is: \n", new_array)
# Q6.2. Write a code to swap row 0 with row 1.
current_array = arr[[1,0,2],:]
print("New array after swap row 0 with row 1 is: \n", current_array)

New array after swap column 1 with column 2 is: 
 [[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]
New array after swap row 0 with row 1 is: 
 [[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
